services:
  postgres:
    image: postgres:15
    container_name: finance_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  postgres_test:
    image: postgres:15
    container_name: finance_postgres_test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    ports:
      - "55432:5432"
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: finance_redis
    ports:
      - "6379:6379"

  # backend:
  #   build: ./finance_backend
  #   container_name: finance_backend
  #   env_file: .env.docker
  #   depends_on:
  #     - postgres
  #     - redis
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./finance_backend:/app

volumes:
  pgdata: