"""
Rename user and transaction tables to users and transactions
Revision ID: 2e71ad04a34e
Revises: ffc517b237d0
Create Date: 2025-08-25 15:04:42.886540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e71ad04a34e'
down_revision: Union[str, Sequence[str], None] = 'ffc517b237d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """Upgrade schema safely by renaming tables."""

    # Rename tables
    op.rename_table('user', 'users')
    op.rename_table('transaction', 'transactions')

    # Update foreign keys
    op.drop_constraint('account_user_id_fkey', 'account', type_='foreignkey')
    op.create_foreign_key(
        None,
        'account',          # source table
        'users',            # target table (renamed)
        ['user_id'],        # local cols
        ['id']              # remote cols
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema safely by renaming tables back."""
    
    # Update foreign keys
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key(
        'account_user_id_fkey',
        'account',          # source table
        'user',             # original table name
        ['user_id'],        # local cols
        ['id']              # remote cols
    )

    # Rename tables back
    op.rename_table('users', 'user')
    op.rename_table('transactions', 'transaction')
