"""add new field is_outgoing in transaction table

Revision ID: 625b860aafa4
Revises: f6c7c95c8934
Create Date: 2025-11-10 17:34:57.689662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '625b860aafa4'
down_revision: Union[str, Sequence[str], None] = 'f6c7c95c8934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_outgoing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_outgoing')
    # ### end Alembic commands ###
