"""add per-user unique message_id

Revision ID: e05e3e24ec8a
Revises: c472f4a1cefe
Create Date: 2025-12-15 10:08:43.201168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e05e3e24ec8a'
down_revision: Union[str, Sequence[str], None] = 'c472f4a1cefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('message_id', sa.String(length=255), nullable=True))
    op.create_index('uniq_transactions_user_message', 'transactions', ['user_id', 'message_id'], unique=True, postgresql_where=sa.text('message_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uniq_transactions_user_message', table_name='transactions', postgresql_where=sa.text('message_id IS NOT NULL'))
    op.drop_column('transactions', 'message_id')
    # ### end Alembic commands ###
