"""added two columns is_verified and last_verification_email

Revision ID: ff2fb85122b9
Revises: e8c10954df5b
Create Date: 2025-08-29 15:21:58.095269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff2fb85122b9'
down_revision: Union[str, Sequence[str], None] = 'e8c10954df5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_verification_email', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_verification_email')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
